apiVersion: v1
kind: Service
metadata:
  name: bionexa-backend-svc
  namespace: "2401088"
  labels:
    app: bionexa-backend
spec:
  type: ClusterIP
  selector:
    app: bionexa-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bionexa-frontend-svc
  namespace: "2401088"
  labels:
    app: bionexa-frontend
spec:
  type: LoadBalancer
  selector:
    app: bionexa-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80

